### ISSUE TITLE
Google Fonts link as error

### ISSUE THREAD

**Issue by darius-gylys** [validator/validator#619] opened 2018-03-04 16:07 UTC
Hi, this link of Google Fonts <link href="https://fonts.googleapis.com/css?family=Montserrat|Roboto" rel="stylesheet"> is considered as bad, because of "|" symbol. It is generated by Google Fonts (copy/pasted) and works well, I suppose there should be no error.

**Comment by Arttse** [comment] 2018-03-04 22:43
See [RFC 3986 - Uniform Resource Identifier (URI): Generic Syntax](https://tools.ietf.org/html/rfc3986)

The character `|` is not a [reserved character](https://tools.ietf.org/html/rfc3986#section-2.2) and is not an [unreserved character](https://tools.ietf.org/html/rfc3986#section-2.3), thus it is an illegal character and [percent-encoding](https://tools.ietf.org/html/rfc3986#section-2.1) should be used. In this case instead `|` should be used `%7C`.

**Comment by sideshowbarker** [comment] 2018-03-04 23:16
@darius-gylys thanks for taking time to raise this. @Arttse is right — but to be clear, the relevant spec that the HTML checker and the HTML spec itself follow on this is the current URL standard at https://url.spec.whatwg.org/.

Anyway, this issue is actually a duplicate of #534. See https://github.com/validator/validator/issues/534#issuecomment-313808641 there:
>
> The `|` character (U+007C) isn’t a [valid URL code point][1] per the current URL Standard.
> 
> You can fix URLs with invalid characters by running them through a tool that will [percent encode][2] any characters in them that aren’t [valid URL code points][1].
> 
> One good online tool for percent-encoding URLs is Eric Meyer’s [URL Decoder/Encoder][3].

  [1]: https://url.spec.whatwg.org/#url-code-points
  [2]: https://url.spec.whatwg.org/#percent-encode
  [3]: http://meyerweb.com/eric/tools/dencoder/

**Closed by sideshowbarker** 2018-03-04 23:16 UTC
