### ISSUE TITLE
Is my code valid or not?

### ISSUE THREAD

**Issue by FrankPal** [validator/validator#110] opened 2015-06-23 17:34 UTC
I've been using the "original" validator forever, ten years, perhaps?  
https://validator.w3.org/  It could not have been more simple to cut and paste, and validate by URL.

I tried to validate this project a few minutes ago, 
http://www.ashawayusa.com/EmailTemplate/EmailWimbledon062315.html

it passed, but it said there were two warnings, where I only see one, that isn't really even a warning.  It suggested that I use the new (nu) validator, https://validator.w3.org/nu/

So I did, by cutting and pasting in my URL again.  I get two "info" lines...   that seem to not really matter to me... and it says "document checking completed", but there is no indication regarding if it has passed  or not.  As a test, I introduced an error in my HTML and saw that it did indeed indicate them...  but why not hit us over the head with the nice green "passed" graphic again?  Green was good, red was not...  it was so easy and instantly obvious.   Why retire a nice feature?

**Comment by cvrebert** [comment] 2015-06-23 17:38
Approximate duplicate of #109.

**Comment by sideshowbarker** [comment] 2015-06-24 05:27
> Approximate duplicate of #109.

yeah, see my response at https://github.com/validator/validator/issues/109#issuecomment-114315421

> but there is no indication regarding if it has passed or not.

Giving a binary pass/fail indication isn’t a goal of this tool. See the part of the page at https://validator.w3.org/nu/about.html that says:

> The Nu Html Checker… is intended solely as a checker, not as a pass/fail certification mechanism.

Also see https://validator.w3.org/nu/about.html#why-validate

The purpose of this checker is to help you catch unintended mistakes. If it finds no mistakes, it reports none.

As I noted in #109, we have no plans to add a binary pass/fail indicator, so I’m going ahead and closing out this issue.

**Closed by sideshowbarker** 2015-06-24 05:27 UTC
