### ISSUE TITLE
Validation not supporting aria types / accessibility

### ISSUE THREAD

**Issue by tonyaveniros** [validator/validator#398] opened 2016-11-07 23:28 UTC
It seems that https://validator.w3.org/ is not yet equipped with the following codes:

aria-required="false"
aria-labelledby="neitherLabel"
role="radiogroup"

I am getting this error

Error: Bad value radio for attribute type on element input.
when trying to validate the following HTML on https://validator.w3.org/nu/#file

<fieldset>
<p class="city" id="citypref">Generally, I would prefer to live in...</p>
<br>
<label for="la" id="laLabel">
<br>
<input type="radio" name="city" id="la" value="la" aria-required="false" aria-labelledby="laLabel" role="radiogroup" >Los Angeles, California</label>
<br>
<label for="boston" id="bostonLabel">
<input type="radio" name="city" id="boston" value="boston" aria-required="false" aria-labelledby="bostonLabel" role="radiogroup" >Boston, Massachusetts</label>
<br>
<label for="both" id="bothLabel">
<input type="radio" name="city" id="both" value="both" aria-required="false" aria-labelledby="bothLabel" role="radiogroup" >Both</label>
<br>
<label for="neither" id="neitherLabel">
<input type="radio" name="city" id="neither" value="neither" aria-required="false" aria-labelledby="neitherLabel" role="radiogroup" >Neither</label>
<br>
</fieldset>

See also: http://stackoverflow.com/questions/40446061/validation-errors-on-nu-html-checker/40470172#40470172

**Comment by nschonni** [comment] 2016-11-08 00:47
As @stevefaulkner pointed out in the answer already http://stackoverflow.com/a/40470172/455535 the role is incorrect on an `<input>`

**Comment by AmeliaBR** [comment] 2016-11-08 01:12
This is still a problem with the validator, in that it is giving a confusing and unhelpful warning.

The problem isn't with a bad value for the `type` attribute, the problem is with a conflicting ARIA role. Given that native HTML takes precedence over ARIA in this case, the correct warning would be something along the lines of 

> Value `radiogroup` for attribute `role` is not allowed on element `input`.

or

> Value `radiogroup` for attribute `role` is not allowed on element `input` when the `type` attribute has value `radio`.

**Comment by nschonni** [comment] 2016-11-08 01:29
> Value `radiogroup` for attribute `role` is not allowed on element input.

That does sound clearer.

**Comment by sideshowbarker** [comment] 2016-11-08 02:03
> This is still a problem with the validator, in that it is giving a confusing and unhelpful warning.

Agreed that better wording in the message here would be much more helpful.

> > Value `radiogroup` for attribute `role` is not allowed on element `input`.

> or

> > Value `radiogroup` for attribute `role` is not allowed on element `input` when the `type` attribute has value `radio`.

Ideally that would clearly be much better. In practice though I can’t make the checker report messages in that form—at least not without spending many more hours completely rewriting the entirety of ARIA checking on the backend—especially for that case of the `input` element, which isn’t really one element but instead ~20 different cases with completely different behavior and rendering and ARIA requirements based on what the value of the `type` attribute is.

The ARIA checking logic is already by far the most complicated part of the backend of the checker and already by far the part that has cost the most development hours (and testing hours and bug-fixing hours…). So while I well recognize the deficiency in the (un)helpfulness of the messages here, it’s unlikely I’m going to be able to improve them significantly unless I magically somehow get a lot smarter and/or end up with an endless supply of more time to put into it.

**Comment by sideshowbarker** [comment] 2016-12-11 12:57
Closing per https://github.com/validator/validator/issues/398#issuecomment-259023870

**Closed by sideshowbarker** 2016-12-11 12:57 UTC
