### ISSUE TITLE
File an issue report

### ISSUE THREAD

**Issue by u6nu83** [validator/validator#349] opened 2016-09-06 03:04 UTC
http://luciya.web.hdv.tw/sandolly_web/search/index
This page's languages is  "zh-hans" not "en"

**Comment by stevefaulkner** [comment] 2016-09-06 07:55
I think the problem is that a subtsantial amount of the content in the page is in English. Where you have a document that includes multiple languages you need to specify the change in language. For example on the containers for the blocks that contain english language text use lang="en"

**Comment by sideshowbarker** [comment] 2016-09-27 02:52
I made a change to the language detector recently and that appears to have eliminated the language-misidentification problem for the document reported here.

So I am going to close this issue for now. But if the problem re-occurs or you find other documents that get misidentified as the wrong language, please file a new issue here.

**Closed by sideshowbarker** 2016-09-27 02:52 UTC
