### ISSUE TITLE
Nu HTML Checker throwing errors on Google Map links

### ISSUE THREAD

**Issue by TedSarah** [validator/validator#312] opened 2016-06-26 20:15 UTC
There are a lot of errors being thrown on Google Map links for files run against Nu HTML Checker.

The error is: "Bad value https://www.google.com/maps/place/22°34'N 59°32'E/data=!4m2!3m1!1s0x0:0x0 for attribute href on element a: Illegal character in path segment: space is not allowed."

The space in question is probably the space between the 34'N and 59°  This is Google's format and, as far as I know, can't be changed.

Can this be corrected do it doesn't throw "errors" for these.

Thanks,

Ted

**Comment by cvrebert** [comment] 2016-06-26 20:23
How are you obtaining these URLs with literal spaces in them?

> and, as far as I know, can't be changed.

Replacing the space with `%20` (i.e. applying percent-encoding) appears to work fine. Have you tried that?

**Comment by TedSarah** [comment] 2016-06-26 20:33
They are coming directly from Google in the URL for the map.

I haven't tried %20, and as you say it'll work.  But, I have a lot of them, and there's no easy way to search and replace them.

**Comment by cvrebert** [comment] 2016-06-26 20:35
> They are coming directly from Google

Via some API, or the browser's URL bar, or some field in the Maps UI, or...?

**Comment by TedSarah** [comment] 2016-06-26 20:49
The browsers URL bar

**Comment by TedSarah** [comment] 2016-06-26 20:53
And, these are coordinates and in different format.  Which makes it harder to replace spaces.

**Comment by cvrebert** [comment] 2016-06-26 20:58
Which browser are you using?

**Comment by TedSarah** [comment] 2016-06-26 20:59
Currently Chrome, but sometimes Firefox

**Comment by cvrebert** [comment] 2016-06-26 21:21
So, the validator merely enforces the standards; it typically doesn't add exemptions to requirements imposed by the standards. The relevant standard in this case is https://url.spec.whatwg.org , and the place to file issues regarding it would be https://github.com/whatwg/url/issues . Get the spec changed, and then the validator can get updated to reflect the revised spec. But there are good reasons to disallow spaces in URLs, so I wouldn't get your hopes up.

FWIW, I can't seem to reproduce your problem. For your example URL, I get redirected to a URL beginning with https://www.google.com/maps/place/22°34'00.0"N+59°32'00.0"E in both Chrome and Firefox, which has a plus-sign instead of a space.

**Comment by TedSarah** [comment] 2016-06-26 21:43
I'm going to try and come up with a way to replace the spaces the various formats.

**Comment by sideshowbarker** [comment] 2016-06-29 05:48
Closing, since as far as the checker behavior goes, it is behaving as expected, because spaces are definitely not allowed in URLs.

> FWIW, I can't seem to reproduce your problem. For your example URL, I get redirected to a URL beginning with https://www.google.com/maps/place/22°34'00.0"N+59°32'00.0"E in both Chrome and Firefox, which has a plus-sign instead of a space.

Same here.

**Closed by sideshowbarker** 2016-06-29 05:48 UTC
