### ISSUE TITLE
Validation using a custom RELAX NG schema ignores an "except" constraint on attribute values

### ISSUE THREAD

**Issue by vadz** [validator/validator#89] opened 2015-04-08 13:29 UTC
Using
```xml
<?xml version="1.0"?>
<resource xmlns="http://www.wxwidgets.org/wxxrc" version="2.5.3.0">
<object class="wxPanel" name="payment_panel">
    <object class="wxFlexGridSizer">
        <foo/>
    </object>
</object>
</resource>
```
(either as a file upload or inline) with the parser set to "XML: load external entities" and the schema from http://www.zeitlins.org/wx/xrc_schema.rnc (this is actually the same schema as the one at the canonical URI http://www.wxwidgets.org/wxxrc, but currently the latter one is returned using `text/plain` content type and so can't be used) unexpectedly validates the document whereas using Jing from the command line correctly gives
```
t.xrc:5:15: error: element "foo" not allowed here; expected the element end-tag or element "cols", "flexibledirection", "growablecols", "growablerows", "hgap", "minsize", "nonflexiblegrowmode", "object", "object_ref", "rows" or "vgap"
```

Notice that some kind of validation is performed because e.g. using `bar` instead of `name` attribute does result in an error. But clearly it doesn't work fully, somehow.

**Comment by sideshowbarker** [comment] 2015-04-10 08:02
> the schema from http://www.zeitlins.org/wx/xrc_schema.rnc (this is actually the same schema as the one at the canonical URI http://www.wxwidgets.org/wxxrc

Those  schemas seem to have some differences, actually. That said, the differences aren’t relevant for the purposes of this issue, since both schemas have exactly the same definition for the `object` element:

```
    element object {
        attribute class { string - allPossibleBuiltinClassNames } &
        stdObjectNodeAttributes &
        anyXMLContent*
    }
```
and they also define `anyXMLContent` in exactly the same way:
```
# Helper for specifying arbitrary content.
anyXMLContent =
  element * {
    (attribute * { text }
     | text
     | anyXMLContent)*
  }
```
As far as I can see, they both allow any arbitrary content within `object`: any element or text.

So the validator seems be working as expected here.

> whereas using Jing from the command line correctly gives
> 
> `t.xrc:5:15: error: element "foo" not allowed here; expected the element end-tag or element`

I don’t see how you could be getting that error message using the schema you cited and the document instance you posted here.

**Comment by vadz** [comment] 2015-04-10 14:07
Thanks for looking at this!

> Those schemas seem to have some differences, actually.

Sorry, the official one got updated/fixed in the meanwhile (and so should be used now).

> As far as I can see, they both allow any arbitrary content within object: any element or text.

Maybe there is a mistake in the schema but this is not how it's supposed to work. It does allow elements with unknown class names, i.e. `<object class="foo">` would be fine, but it validates the elements with the known names, such as `wxFlexGridSizer`.

> I don’t see how you could be getting that error message using the schema you cited and the document instance you posted here.

Right now, using the [latest Jing](https://github.com/vadz/jing-trang) I get:
{{{
% cat -n t.xrc
     1  <?xml version="1.0"?>
     2  <resource xmlns="http://www.wxwidgets.org/wxxrc" version="2.5.3.0">
     3  <object class="wxPanel" name="payment_panel">
     4      <object class="wxFlexGridSizer">
     5          <foo/>
     6      </object>
     7  </object>
     8  </resource>
% java -jar jing.jar -c http://www.wxwidgets.org/wxxrc t.xrc
t.xrc:5:15: error: element "foo" not allowed here; expected the element end-tag or element "cols", "flexibledirection", "growablecols", "growablerows", "hgap", "minsize", "nonflexiblegrowmode", "object", "object_ref", "rows" or "vgap"
}}}

If the schema is really wrong, I don't understand why does it work. And though this is perhaps too much to ask, would you have any suggestions about how to modify it to do what we really want, i.e. allow unknown object classes while still validating the contents of the known ones?

But the question of inconsistency between the local Jing and the online validator still remains in any case.

**Comment by sideshowbarker** [comment] 2015-04-10 15:14
> But the question of inconsistency between the local Jing and the online validator still remains in any case.

As far as that goes, after doing some testing I find that’s due to the fact the validator uses a different version of jing—a fork that we branched off from the jing trunk specifically for use with the validator. So it seems we might have a bug in our fork. Because testing with the jing trunk code and also with the `rnv` validator, I find that both report an error for that `foo` element for me in my environment.

> would you have any suggestions about how to modify it to do what we really want, i.e. allow unknown object classes while still validating the contents of the known ones?

I don’t have suggestions right now. I’ll need to look at the schema a little further to figure out why not already working everywhere the way you describe.

In the mean time, maybe @georgebina might be able to chime in here with some insight.

**Comment by vadz** [comment] 2015-04-10 15:20
BTW, this has nothing to do with this bug directly, but seeing that both you and @georgebina seem to have been part of jing project at (the soon to be defunct) Google code, I'd be glad to pass ownership of [my clone](https://github.com/vadz/jing-trang) of it to you, as I wrote [there](https://code.google.com/p/jing-trang/issues/detail?id=195) if you're interested.

**Comment by sideshowbarker** [comment] 2015-04-10 15:29
> BTW, this has nothing to do with this bug directly, but seeing that both you and @georgebina seem to have been part of jing project at (the soon to be defunct) Google code, I'd be glad to pass ownership of my clone of it to you, as I wrote there if you're interested.

Thanks yeah we do plan on migrating the upstream repo out of Google Code and into github but we are still deciding whether to put it under https://github.com/jclark or instead to create a new github org.

**Comment by vadz** [comment] 2015-04-10 15:31
The point is that whatever you decide, I think you could just take over the existing repo (and rename it) instead of redoing the process. It's not that complicated to redo, of course, but still involves some manual steps, so I just thought I could save a little time for you.

**Comment by sideshowbarker** [comment] 2015-04-10 15:32
So it seems the cause of the different behavior in the validator jing fork is that it’s ignoring the `string - allPossibleBuiltinClassNames` constraint in the `attribute class { string - allPossibleBuiltinClassNames }` part of the definition of the `customClasses` flavor of the `object` element. In other words, it seems to be treating all instances of the `object` element, regardless of their `class` value, as being the  `customClasses` flavor, and so allowed to have any arbitrary content.

**Comment by sideshowbarker** [comment] 2015-04-10 15:36
> The point is that whatever you decide, I think you could just take over the existing repo (and rename it) instead of redoing the import process. It's not that complicated to redo, of course, but still involves some manual steps, so I just thought I could save a little time for you.

Thanks yeah OK you’re right—when it comes time to actually do it, I think you could just push a button to transfer it over to https://github.com/jclark so that’s most likely what we’ll end up doing.

**Comment by georgebina** [comment] 2015-04-11 04:28
The problem may be related to this fixed Jing issue:
https://code.google.com/p/jing-trang/issues/detail?id=82

**Comment by sideshowbarker** [comment] 2015-04-11 04:31
Hi @georgebina
> The problem may be related to this fixed Jing issue:
> https://code.google.com/p/jing-trang/issues/detail?id=82

Aha—thanks, I’ll try porting that change to our branch and see if that fixes it

**Comment by sideshowbarker** [comment] 2015-04-11 05:20
@georgebina tested porting that change over locally in my working directory and indeed that does fix it (that is, it causes an error message for the `foo` element to be emitted as expected). Thanks again. I'll push the change to our jing branch within the next couple days.

**Comment by georgebina** [comment] 2015-04-11 06:53
Happy to hear that was indeed the issue.
Ideally you should try to merge the current Jing trunk - or at least you can look at the commit history 
https://code.google.com/p/jing-trang/source/list
and check the associated issues to see if there are some other fixes that you want to get to your branch.

All the best,
George

**Comment by sideshowbarker** [comment] 2015-04-11 07:16
Unfortunately I think at this point our branch has  diverged so much from the trunk, while also some refactorings were done on the trunk itself, that there's no way we could merge the trunk without a lot of additional manual coding needing to be done. And really our branch is a special thing that's sorta optimized for the particular needs of the validator and not really meant to be used anywhere else.

So anyway I will do what you suggest and look through the commit history on the trunk to see what else we should port over. Thanks again!

**Comment by sideshowbarker** [comment] 2015-06-28 02:03
Already ported over the fix, so will go ahead and close this.

**Closed by sideshowbarker** 2015-06-28 02:03 UTC
Labels: known issue
