### ISSUE TITLE
https://validator.w3.org/check?uri=referer no longer (?) checking actual referer, but my homepage

### ISSUE THREAD

**Issue by PeterBDa** [validator/validator#1136] opened 2021-04-15 14:20 UTC
All my webpages contain this link, however I notice that all links now result in the checking of my home page, and not the actual referer. I'm sure this didn't use to be the case (but last checked long ago)

**Comment by sideshowbarker** [comment] 2021-04-15 14:50
Please re-raise this at https://github.com/w3c/markup-validator/

**Comment by HeartbliT** [comment] 2021-04-16 01:10
Duplicate of #113

**Closed** 2021-04-16 01:55 UTC
