### ISSUE TITLE
Bug with pre tag?

### ISSUE THREAD

**Issue by rowedahelicon** [validator/validator#590] opened 2018-01-02 06:50 UTC
Unsure if it is a validator error or a matter of flow, but having a `<div>` inside of an `<a>` will return the error: **Element div not allowed as child of element a in this context.** if it is contained within a `<pre>` tag. The error displayed the recommendations aren't consistent with the root problem as it implies the div tag is the cause for the error.

**Comment by cvrebert** [comment] 2018-01-02 07:05
Duplicate of #569 ?

**Comment by sideshowbarker** [comment] 2018-01-02 07:06
> Duplicate of #569 ?

Yeah, probably so, I guess.

@rowedahelicon What’s the parent element of that `<a>` when you got that error message?

**Comment by rowedahelicon** [comment] 2018-01-02 07:10
@sideshowbarker Unsure if a duplicate, the parent element of the `<a>` is simply a `<pre>`, if I change it to a `<section>` or a `<div>` the error goes away entirely

**Comment by sideshowbarker** [comment] 2018-01-02 07:33
OK, `pre` elements can only have phrasing content as descendants:

https://html.spec.whatwg.org/multipage/grouping-content.html#the-pre-element

That means an `a` element inside a `pre` can’t contain a `div` — because a `div` isn’t phrasing content.

So yeah it’s the same general problem as #569 — the error message should be improved.

**Comment by sideshowbarker** [comment] 2018-01-29 01:08
I’m gonna go ahead and close this since we have #569 already (and I re-titled that to make it more general)

**Closed by sideshowbarker** 2018-01-29 01:08 UTC
Labels: better-error-warning-message
