### ISSUE TITLE
itemprop="mainEntityOfPage" - Error: Element META is missing required attribute CONTENT.

### ISSUE THREAD

**Issue by M2spbRu** [validator/validator#263] opened 2016-03-19 15:36 UTC
In web page http://www.m2-spb.ru/com01_print_test
I've used itemprop="mainEntityOfPage" without attribute CONTENT.

From https://validator.w3.org/nu/?doc=http%3A%2F%2Fwww.m2-spb.ru%2Fcom01_print_test
I've got "Error: Element META is missing required attribute CONTENT"

From https://developers.google.com/structured-data/testing-tool/
and from http://www.onlinewebcheck.com/check.php
I've got "0 error messages".

Where is the truth?

**Comment by stevefaulkner** [comment] 2016-03-19 16:02
Hi @M2spbRu 

>Where is the truth?

The related HTML conformance requirement for `<meta>` is:

> Exactly one of the name, http-equiv, charset, and itemprop attributes must be specified.
> If either name, http-equiv, or itemprop is specified, then the content attribute must also be specified. Otherwise, it must be omitted.
https://w3c.github.io/html/document-metadata.html#the-meta-element

So use of `itemprop` on `<meta>` without a `content` attribute is non conforming in HTML.

**Comment by unor** [comment] 2016-03-19 19:20
I think this is a duplicate of https://github.com/validator/validator/issues/192.

Google’s Microdata example [is invalid](http://stackoverflow.com/a/34467088).

If you want to give a URL value for the `mainEntityOfPage` property, you [must](http://stackoverflow.com/a/24659620/1591669) use a `link` element:

    <link itemprop="mainEntityOfPage" href="http://www.m2-spb.ru/com01">

(In that case you can’t provide a type like `WebPage` for the document; it’s [either an item with type (in which case you need something like `div`), or a URL](http://stackoverflow.com/a/34245547/1591669).)

**Comment by sideshowbarker** [comment] 2016-03-19 19:43
Yeah the Microdata section of the HTML spec (which @stevefaulkner cited) is very clear on this. So as @unor noted, Google has an invalid example in their docs. If you think that example should in fact be valid, you should file an issue against the HTML spec https://github.com/whatwg/html/issues/new (since the HTML spec is the single ultimate source of truth here).

Short of that, I can’t make this a non-error in the checker—because the checker must conform to the requirements in the HTML spec (though I do realize it would be good to have an error message for this case that’s more helpful than the current one is).

As far as how to mark it up in a way that’s not an error per the HTML spec, I recommend paying attention to anything unor suggests, because in my experience with discussions about this stuff here and at StackOverflow, unor has more insight in how to use Microdata and RDFa productively in the real-world than pretty much anybody else.

**Comment by M2spbRu** [comment] 2016-03-20 14:14
So I need to use empty content attribute.
And it is not the error. 
Is it right? ‎

**Comment by sideshowbarker** [comment] 2016-03-20 15:11
> So I need to use empty content attribute.
> And it is not the error. 
> Is it right? 

No, that's not right. You need to instead do add @unor suggested, and use s `link` element instead:

> <link itemprop="mainEntityOfPage" href="http://www.m2-spb.ru/com01">

**Comment by M2spbRu** [comment] 2016-03-20 17:32
Thank you, @unor and @sideshowbarker !
It works :)

**Closed** 2016-03-26 14:03 UTC
