### ISSUE TITLE
The links to attribute definitions are broken in W3C version

### ISSUE THREAD

**Issue by takenspc** [validator/validator#272] opened 2016-04-01 00:55 UTC
Nu Html Checker includes the links to attribute definitions in the error messages.

For example,
https://validator.w3.org/nu/?doc=data%3Atext%2Fhtml%2C%3C!doctype+html%3E%3Chtml+dummy%3E

> <dl>
> <dt>Attributes for element <a href="http://www.w3.org/html/wg/drafts/html/master/single-page.html#the-html-element"><code>html</code></a>:</dt>
> <dd><a href="http://www.w3.org/html/wg/drafts/html/master/single-page.html#global-attributes">Global attributes</a></dd>
> <dd><code><a href="http://www.w3.org/html/wg/drafts/html/master/single-page.html#attr-html-manifest">manifest</a></code></dd>
> </dl>

I noticed that the links to attribute definitions (“manifest” in the previous example) are now broken because W3C HTML changed fragments.

Note: links of checker.html5.org are not broken.
https://checker.html5.org/?doc=data%3Atext%2Fhtml%2C%3C!doctype+html%3E%3Chtml+dummy%3E

I will be happy if this issue is fixed though I’m doubtful that Nu Html Checker should fix this...

[html]: http://www.w3.org/html/wg/drafts/html/master/single-page.html#the-html-element
[Global attributes]: http://www.w3.org/html/wg/drafts/html/master/single-page.html#global-attributes
[manifest]: http://www.w3.org/html/wg/drafts/html/master/single-page.html#attr-html-manifest

**Comment by sideshowbarker** [comment] 2016-05-02 16:48
> I will be happy if this issue is fixed though I’m doubtful that Nu Html Checker should fix this...

Yeah, I don’t know how to fix this since the problem seems to be that the changes made to the anchors in the W3C HTML spec broke it. I guess I would suggest filing a bug at https://github.com/w3c/html/issues to ask the editors to un-break those anchors—which are broken not only for the checker but for existing links that others have created to those anchors.

**Comment by sideshowbarker** [comment] 2016-05-07 16:24
I’m closing this because while I agree the current W3C HTML spec snippets that the checker now outputs are a regression that’s bad for users—in that the links to the spec definitions for attributes are now gone. But that’s not something I can fix on the checker code, so I encourage you to file a bug against the W3C HTML spec so they can fix it—and after they do, we can update the spec copy in the checker sources.

**Closed by sideshowbarker** 2016-05-07 16:24 UTC
Labels: not a bug
