### ISSUE TITLE
<object typemustmatch> should be invalid

### ISSUE THREAD

**Issue by zcorpan** [validator/validator#862] opened 2019-09-02 16:24 UTC
```
<!DOCTYPE html>
<html>
<head>
<title>Test</title>
</head>
<body>
<p><object typemustmatch data=x type=image/png></object></p>
</body>
</html>
```

> The document validates according to the specified schema(s).

See https://github.com/whatwg/html/pull/4590

**Comment by sideshowbarker** [comment] 2019-09-03 01:22
Duplicate of #855; Fixed in 759fb87

**Closed by sideshowbarker** 2019-09-03 01:22 UTC
