### ISSUE TITLE
<meta> tags with @proeprty attribute on <body>: error or warning?

### ISSUE THREAD

**Issue by gjvnq** [validator/validator#1018] opened 2020-08-25 02:02 UTC
Currently, writing code like this leads to an error.

```html
<meta itemprop="name" property="name" content="T.B. Lee">
```

However, the [RDFa in XHTML: Syntax and Processing](https://www.w3.org/TR/rdfa-syntax/#sec_6.3.1.1.) shows this example:

> ```html
> <meta about="http://internet-apps.blogspot.com/"
>      property="dc:creator" content="Mark Birbeck" />
> ```

While this is within the ```<head>```, it isn't clear wether doing the same is forbidden or just not recommended. Thus, it may be appropriate to change this from an error to a warning.

**Comment by sideshowbarker** [comment] 2020-08-25 04:13
The cause of the error in this case is that the `meta` element has both a `property` attribute and an `itemprop` attribute. The error can be eliminated by dropping one attribute or the other; that is, either of the following will work:

```
<meta itemprop="name" content="T.B. Lee">
```
or
```
<meta property="name" content="T.B. Lee">
```

**Comment by sideshowbarker** [comment] 2021-05-21 11:43
Closing per https://github.com/validator/validator/issues/1018#issuecomment-679575253

**Closed by sideshowbarker** 2021-05-21 11:43 UTC
