### ISSUE TITLE
Missing </html> doesn't throw an error

### ISSUE THREAD

**Issue by ianhiatt** [validator/validator#1038] opened 2020-10-25 12:36 UTC
When doing an upload/direct input no error is thrown if the </html> tag is missing. Example:

[hello_world.txt](https://github.com/validator/validator/files/5434716/hello_world.txt)

As most HTML is forgiving, this of course works. But best practice is to close all tags that are opened. This should throw an error/warning.

**Comment by cvrebert** [comment] 2020-10-25 15:55
Duplicate of #658

Please search for relevant closed issues in the future when filing new issues.

**Comment by ianhiatt** [comment] 2020-10-25 16:49
I did a search and the above didn't appear. Please don't assume laziness.

Shouldn't this still warrant a warning? Plenty of other warnings appear for "optional" things. You get warnings for images without alt tags for example.

**Comment by sideshowbarker** [comment] 2020-10-26 02:40
We don’t warn about it because there are no problems that it causes. And the HTML language and browsers have from the beginning always allowed the `</html>` end tag to be omitted from document. There was never a time when either the HTML specification or browsers required the `</html>` end tag.

It’s true that XML and “XHTML” required every element to have an end tag, but HTML isn’t either XML. HTML is its own language, with its own rules — and “every element must have an end tag” is not one of its rules.

**Closed** 2020-11-19 02:26 UTC
