### ISSUE TITLE
Validator loses track of custom variables defined in separate <style> blocks

### ISSUE THREAD

**Issue by tmb-github** [validator/validator#1404] opened 2022-07-23 14:52 UTC
Variables defined in one style block are not being recognized in other style blocks in certain cases. See the following:

```
<!doctype html>
<html lang=en-us>
<title>CSS problem</title>
<style class=global-styles>
:root {
    --header-height: 60px;
}
</style>
<style class=local-styles>
.minified{margin:calc(1em + var(--header-height)) 6.5% 2em 6.5%;outline:0}
.beautified{
    margin: calc(1em + var(--header-height)) 6.5% 2em 6.5%;
    outline:0;
}
</style>
</html>
```
For line 10, the validator throws this error:

> Error: CSS: margin: The types are incompatible.
> 
> [From line 10, column 60; to line 10, column 63](https://validator.w3.org/nu/?showsource=yes&showoutline=yes&doc=https%3A%2F%2Fthomasbrodhead.com%2F#l10c63)
> 
>  6.5% 2em 6.5%;outli

For line 12, it throws a similar error:

> Error: CSS: margin: The types are incompatible.
> 
> [From line 12, column 55; to line 12, column 58](https://validator.w3.org/nu/?showsource=yes&showoutline=yes&doc=https%3A%2F%2Fthomasbrodhead.com%2F#l12c58)
> 
>  6.5% 2em 6.5%;↩

If the two style blocks are consolidated, however, the validator issues no error messages:

```
<!doctype html>
<html lang=en-us>
<title>CSS problem</title>
<style>
:root {
    --header-height: 60px;
}


.minified{margin:calc(1em + var(--header-height)) 6.5% 2em 6.5%;outline:0}
.beautified{
    margin: calc(1em + var(--header-height)) 6.5% 2em 6.5%;
    outline:0;
}
</style>
</html>
```

**Comment by nschonni** [comment] 2022-07-23 15:28
Likely needs to be raised on https://github.com/w3c/css-validator

**Comment by tmb-github** [comment] 2022-07-23 15:35
@nschonni It does not produce an error when run on that validator (https://jigsaw.w3.org/css-validator/validator). Try it and see.

The error seems to be in the HTML parsing of the two <style> tags performed by the validation routine of this validator. (It seems to be validating the two style areas independently.)

**Comment by nschonni** [comment] 2022-07-24 00:56
Actually, I think this is a duplicate of https://github.com/validator/validator/issues/1284, not related to the split styles

**Comment by sideshowbarker** [comment] 2022-10-29 05:07
@tmb-github Does the checker still report an unexpected error here? I think the cause was subsequently fixed.

**Comment by tmb-github** [comment] 2022-10-29 05:42
@sideshowbarker It no longer throws those errors when I test it against the example I submit, nor against my own live site code, so it seems to be fixed. Many thanks!

**Comment by sideshowbarker** [comment] 2022-10-29 05:52
@tmb-github cheers 🥂 — thanks for confirming

**Closed by sideshowbarker** 2022-10-29 05:52 UTC
