### ISSUE TITLE
Support text-justify: inter-character value as valid css

### ISSUE THREAD

**Issue by hunboy** [validator/validator#758] opened 2019-02-08 01:18 UTC
Currently validator says
Error: CSS: text-justify: inter-character is not a text-justify value.

Add this value as valid css.

https://developer.mozilla.org/en-US/docs/Web/CSS/text-justify
https://drafts.csswg.org/css-text-3/#text-justify-property

**Comment by sideshowbarker** [comment] 2019-02-11 03:08
I believe this fixed in the sources now by https://github.com/w3c/css-validator/commit/095c7a1c9ff0696399984881390b9be81d236df1 — and pushed to https://validator.w3.org/nu/

**Comment by sideshowbarker** [comment] 2019-02-11 03:09
Thanks much for reporting this

**Closed by sideshowbarker** 2019-02-11 03:08 UTC

**Comment by ylafon** [comment] 2019-02-11 11:19
Note that it always difficult to figure out when to update implementation of a specification that is still in WD. 
https://caniuse.com/#search=text-justify report that the implementation status is not great yet, so it is highly possible that this will change again in the future...

**Comment by sideshowbarker** [comment] 2019-02-11 11:52
> https://caniuse.com/#search=text-justify report that the implementation status is not great yet

hmm yeah — In hindsight that makes me think maybe we should have waited before adding checker support for it…

**Comment by ylafon** [comment] 2019-02-11 12:10
The issue is that some properties already defined in CSS2 got an update, so it was ok for a partial implementation, something a bit more difficult to track.
