### ISSUE TITLE
NoClassDefFoundError: Could not initialize class nu.validator.datatype.SourceSizeList

### ISSUE THREAD

**Issue by cvrebert** [validator/validator#308] opened 2016-06-20 07:14 UTC
When trying to update LMVTFY to use the latest JAR (16.6.18), I encounter the following error:
```
[error]    NoClassDefFoundError: : Could not initialize class nu.validator.datatype.SourceSizeList  (Html5DatatypeLibrary.java:176)
[error] nu.validator.datatype.Html5DatatypeLibrary.createDatatype(Html5DatatypeLibrary.java:176)
[error] nu.validator.datatype.Html5DatatypeLibrary.createDatatypeBuilder(Html5DatatypeLibrary.java:53)
[error] com.thaiopensource.relaxng.impl.SchemaBuilderImpl.makeDataPatternBuilder(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.DataExpr(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.PrimaryExpr(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.AnnotatedPrimaryExpr(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.UnaryExpr(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.Expr(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.Define(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.Definition(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.GrammarComponent(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.GrammarBody(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.IncludedGrammar(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.parseInclude(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactParseable.parseAsInclude(Unknown Source)
[error] com.thaiopensource.relaxng.impl.SchemaBuilderImpl$IncludeImpl.endInclude(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.Include(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.GrammarComponent(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.GrammarBody(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.IncludedGrammar(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.parseInclude(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactParseable.parseAsInclude(Unknown Source)
[error] com.thaiopensource.relaxng.impl.SchemaBuilderImpl$IncludeImpl.endInclude(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.Include(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.GrammarComponent(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.GrammarBody(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.TopLevelGrammar(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.Input(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.parse(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactParseable.parse(Unknown Source)
[error] com.thaiopensource.relaxng.impl.SchemaBuilderImpl.parse(Unknown Source)
[error] com.thaiopensource.relaxng.impl.SchemaReaderImpl.createSchema(Unknown Source)
[error] com.thaiopensource.validate.AbstractSchemaReader.createSchema(Unknown Source)
[error] nu.validator.validation.SimpleDocumentValidator.schemaByUrl(SimpleDocumentValidator.java:125)
[error] nu.validator.validation.SimpleDocumentValidator.setUpMainSchema(SimpleDocumentValidator.java:175)
[error] com.chrisrebert.lmvtfy.validation.Html5Validator.validator$lzycompute(Html5Validator.scala:83)
[error] com.chrisrebert.lmvtfy.validation.Html5Validator.validator(Html5Validator.scala:82)
[error] com.chrisrebert.lmvtfy.validation.Html5Validator.validationErrors$lzycompute(Html5Validator.scala:52)
[error] com.chrisrebert.lmvtfy.validation.Html5Validator.validationErrors(Html5Validator.scala:51)
[error] com.chrisrebert.lmvtfy.validation.Html5Validator$.validationErrorsFor(Html5Validator.scala:42)
[error] ValidatorSpec$$anonfun$1$$anonfun$apply$1.apply(ValidatorSpec.scala:24)
[error] ValidatorSpec$$anonfun$1$$anonfun$apply$1.apply(ValidatorSpec.scala:23)
```

I presume there's some minor mistake in the generation of the JAR.

**Comment by cvrebert** [comment] 2016-06-20 07:20
In some cases, the error is different but related:
```
[error]    ExceptionInInitializerError:   (SourceSizeList.java:44)
[error] nu.validator.datatype.SourceSizeList.<clinit>(SourceSizeList.java:44)
[error] nu.validator.datatype.Html5DatatypeLibrary.createDatatype(Html5DatatypeLibrary.java:176)
[error] nu.validator.datatype.Html5DatatypeLibrary.createDatatypeBuilder(Html5DatatypeLibrary.java:53)
[error] com.thaiopensource.relaxng.impl.SchemaBuilderImpl.makeDataPatternBuilder(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.DataExpr(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.PrimaryExpr(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.AnnotatedPrimaryExpr(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.UnaryExpr(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.Expr(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.Define(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.Definition(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.GrammarComponent(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.GrammarBody(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.IncludedGrammar(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.parseInclude(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactParseable.parseAsInclude(Unknown Source)
[error] com.thaiopensource.relaxng.impl.SchemaBuilderImpl$IncludeImpl.endInclude(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.Include(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.GrammarComponent(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.GrammarBody(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.IncludedGrammar(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.parseInclude(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactParseable.parseAsInclude(Unknown Source)
[error] com.thaiopensource.relaxng.impl.SchemaBuilderImpl$IncludeImpl.endInclude(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.Include(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.GrammarComponent(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.GrammarBody(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.TopLevelGrammar(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.Input(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.parse(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactParseable.parse(Unknown Source)
[error] com.thaiopensource.relaxng.impl.SchemaBuilderImpl.parse(Unknown Source)
[error] com.thaiopensource.relaxng.impl.SchemaReaderImpl.createSchema(Unknown Source)
[error] com.thaiopensource.validate.AbstractSchemaReader.createSchema(Unknown Source)
[error] nu.validator.validation.SimpleDocumentValidator.schemaByUrl(SimpleDocumentValidator.java:125)
[error] nu.validator.validation.SimpleDocumentValidator.setUpMainSchema(SimpleDocumentValidator.java:175)
[error] com.chrisrebert.lmvtfy.validation.Html5Validator.validator$lzycompute(Html5Validator.scala:83)
[error] com.chrisrebert.lmvtfy.validation.Html5Validator.validator(Html5Validator.scala:82)
[error] com.chrisrebert.lmvtfy.validation.Html5Validator.validationErrors$lzycompute(Html5Validator.scala:52)
[error] com.chrisrebert.lmvtfy.validation.Html5Validator.validationErrors(Html5Validator.scala:51)
[error] com.chrisrebert.lmvtfy.validation.Html5Validator$.validationErrorsFor(Html5Validator.scala:42)
[error] ValidatorSpec$$anonfun$7$$anonfun$apply$27.apply(ValidatorSpec.scala:158)
[error] ValidatorSpec$$anonfun$7$$anonfun$apply$27.apply(ValidatorSpec.scala:157)
[error] nu.validator.datatype.tools.CssParser.<clinit>(CssParser.java:47)
[error] nu.validator.datatype.SourceSizeList.<clinit>(SourceSizeList.java:44)
[error] nu.validator.datatype.Html5DatatypeLibrary.createDatatype(Html5DatatypeLibrary.java:176)
[error] nu.validator.datatype.Html5DatatypeLibrary.createDatatypeBuilder(Html5DatatypeLibrary.java:53)
[error] com.thaiopensource.relaxng.impl.SchemaBuilderImpl.makeDataPatternBuilder(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.DataExpr(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.PrimaryExpr(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.AnnotatedPrimaryExpr(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.UnaryExpr(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.Expr(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.Define(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.Definition(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.GrammarComponent(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.GrammarBody(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.IncludedGrammar(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.parseInclude(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactParseable.parseAsInclude(Unknown Source)
[error] com.thaiopensource.relaxng.impl.SchemaBuilderImpl$IncludeImpl.endInclude(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.Include(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.GrammarComponent(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.GrammarBody(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.IncludedGrammar(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.parseInclude(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactParseable.parseAsInclude(Unknown Source)
[error] com.thaiopensource.relaxng.impl.SchemaBuilderImpl$IncludeImpl.endInclude(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.Include(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.GrammarComponent(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.GrammarBody(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.TopLevelGrammar(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.Input(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.parse(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactParseable.parse(Unknown Source)
[error] com.thaiopensource.relaxng.impl.SchemaBuilderImpl.parse(Unknown Source)
[error] com.thaiopensource.relaxng.impl.SchemaReaderImpl.createSchema(Unknown Source)
[error] com.thaiopensource.validate.AbstractSchemaReader.createSchema(Unknown Source)
[error] nu.validator.validation.SimpleDocumentValidator.schemaByUrl(SimpleDocumentValidator.java:125)
[error] nu.validator.validation.SimpleDocumentValidator.setUpMainSchema(SimpleDocumentValidator.java:175)
[error] com.chrisrebert.lmvtfy.validation.Html5Validator.validator$lzycompute(Html5Validator.scala:83)
[error] com.chrisrebert.lmvtfy.validation.Html5Validator.validator(Html5Validator.scala:82)
[error] com.chrisrebert.lmvtfy.validation.Html5Validator.validationErrors$lzycompute(Html5Validator.scala:52)
[error] com.chrisrebert.lmvtfy.validation.Html5Validator.validationErrors(Html5Validator.scala:51)
[error] com.chrisrebert.lmvtfy.validation.Html5Validator$.validationErrorsFor(Html5Validator.scala:42)
[error] ValidatorSpec$$anonfun$7$$anonfun$apply$27.apply(ValidatorSpec.scala:158)
[error] ValidatorSpec$$anonfun$7$$anonfun$apply$27.apply(ValidatorSpec.scala:157)
[error] 
[error] Caused by java.lang.NullPointerException: null
[error] nu.validator.datatype.tools.CssParser.<clinit>(CssParser.java:47)
[error] nu.validator.datatype.SourceSizeList.<clinit>(SourceSizeList.java:44)
[error] nu.validator.datatype.Html5DatatypeLibrary.createDatatype(Html5DatatypeLibrary.java:176)
[error] nu.validator.datatype.Html5DatatypeLibrary.createDatatypeBuilder(Html5DatatypeLibrary.java:53)
[error] com.thaiopensource.relaxng.impl.SchemaBuilderImpl.makeDataPatternBuilder(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.DataExpr(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.PrimaryExpr(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.AnnotatedPrimaryExpr(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.UnaryExpr(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.Expr(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.Define(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.Definition(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.GrammarComponent(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.GrammarBody(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.IncludedGrammar(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.parseInclude(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactParseable.parseAsInclude(Unknown Source)
[error] com.thaiopensource.relaxng.impl.SchemaBuilderImpl$IncludeImpl.endInclude(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.Include(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.GrammarComponent(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.GrammarBody(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.IncludedGrammar(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.parseInclude(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactParseable.parseAsInclude(Unknown Source)
[error] com.thaiopensource.relaxng.impl.SchemaBuilderImpl$IncludeImpl.endInclude(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.Include(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.GrammarComponent(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.GrammarBody(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.TopLevelGrammar(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.Input(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactSyntax.parse(Unknown Source)
[error] com.thaiopensource.relaxng.parse.compact.CompactParseable.parse(Unknown Source)
[error] com.thaiopensource.relaxng.impl.SchemaBuilderImpl.parse(Unknown Source)
[error] com.thaiopensource.relaxng.impl.SchemaReaderImpl.createSchema(Unknown Source)
[error] com.thaiopensource.validate.AbstractSchemaReader.createSchema(Unknown Source)
[error] nu.validator.validation.SimpleDocumentValidator.schemaByUrl(SimpleDocumentValidator.java:125)
[error] nu.validator.validation.SimpleDocumentValidator.setUpMainSchema(SimpleDocumentValidator.java:175)
[error] com.chrisrebert.lmvtfy.validation.Html5Validator.validator$lzycompute(Html5Validator.scala:83)
[error] com.chrisrebert.lmvtfy.validation.Html5Validator.validator(Html5Validator.scala:82)
[error] com.chrisrebert.lmvtfy.validation.Html5Validator.validationErrors$lzycompute(Html5Validator.scala:52)
[error] com.chrisrebert.lmvtfy.validation.Html5Validator.validationErrors(Html5Validator.scala:51)
[error] com.chrisrebert.lmvtfy.validation.Html5Validator$.validationErrorsFor(Html5Validator.scala:42)
[error] ValidatorSpec$$anonfun$7$$anonfun$apply$27.apply(ValidatorSpec.scala:158)
[error] ValidatorSpec$$anonfun$7$$anonfun$apply$27.apply(ValidatorSpec.scala:157)
```

**Comment by sideshowbarker** [comment] 2016-06-20 08:13
Odd. I can’t reproduce this. You are using the maven jar file, right? I mean from, e.g.:

https://repo1.maven.org/maven2/nu/validator/validator/16.6.18/validator-16.6.18.jar

When I download and use that in my environment it works as expected.

Anyway I have uploaded a new release 16.6.20 maven release:

https://repo1.maven.org/maven2/nu/validator/validator/16.6.20/validator-16.6.20.jar

Please try that one and let me know if you see the same problem as you do with the 16.6.18.jar

If you do, I am kind of at a loss to figure out what’s going on.

**Comment by sideshowbarker** [comment] 2016-06-20 08:19
> In some cases, the error is different but related:

In that stack trace I see something different mid-way through:

```
[error] Caused by java.lang.NullPointerException: null
[error] nu.validator.datatype.tools.CssParser.<clinit>(CssParser.java:47)
```

**Comment by cvrebert** [comment] 2016-06-20 08:26
> You are using the maven jar file, right?

Yep.

> Anyway I have uploaded a new release 16.6.20 maven release:

Same errors as before, unfortunately.

**Comment by sideshowbarker** [comment] 2016-06-20 08:40
> > You are using the maven jar file, right?
> Yep.
> 
> > Anyway I have uploaded a new release 16.6.20 maven release:
> Same errors as before, unfortunately.

Not sure how to troubleshoot it without being able to reproduce it. And I have been looking through the changes since the last release to see if there’s anything different in the way I’m building the jar, and I am not finding anything.

And as far as the actual file contents of the jar, the only differences I find are this:

```diff
@@ -1,5 +1,5 @@
 " zip.vim version v27
-" Browsing zipfile /private/tmp/validator-16.3.3.jar
+" Browsing zipfile /private/tmp/validator-16.6.18.jar
 " Select a file with cursor and press ENTER

 META-INF/
@@ -64,6 +64,7 @@
 nu/validator/collections/TailBiasedSortedSet.class
 nu/validator/datatype/
 nu/validator/datatype/ARel.class
+nu/validator/datatype/AbstractAutocompleteDetails.class
 nu/validator/datatype/AbstractDatatype$CharSequenceWithOffset.class
 nu/validator/datatype/AbstractDatatype.class
 nu/validator/datatype/AbstractDatetime.class
@@ -72,6 +73,15 @@
 nu/validator/datatype/AbstractUnicodeClassCharacter$1.class
 nu/validator/datatype/AbstractUnicodeClassCharacter.class
 nu/validator/datatype/AsciiCaseInsensitiveString.class
+nu/validator/datatype/AutocompleteDetailsAny.class
+nu/validator/datatype/AutocompleteDetailsDate.class
+nu/validator/datatype/AutocompleteDetailsEmail.class
+nu/validator/datatype/AutocompleteDetailsMonth.class
+nu/validator/datatype/AutocompleteDetailsNumeric.class
+nu/validator/datatype/AutocompleteDetailsPassword.class
+nu/validator/datatype/AutocompleteDetailsTel.class
+nu/validator/datatype/AutocompleteDetailsText.class
+nu/validator/datatype/AutocompleteDetailsUrl.class
 nu/validator/datatype/BrowsingContext.class
 nu/validator/datatype/BrowsingContextOrKeyword.class
 nu/validator/datatype/CdoCdcPair$1.class
```

That is, nothing missing that was there before, and instead just some new additional classes, as expected, for handling the datatype checking for the `autocomplete` attribute.

Maybe @rwhogg can doublecheck the maven jar when he has time.

**Comment by sideshowbarker** [comment] 2016-06-20 08:50
The only other difference I can think of is that I upgraded my java SDK after the 16.3.3 release in March. I have 1.8.0_92 installed now. I can try rolling back to the 1.8.0_72 released I had installed before, and we can see if that makes any difference.

**Comment by cvrebert** [comment] 2016-06-20 08:52
I'm also using 1.8.0_92.

**Comment by sideshowbarker** [comment] 2016-06-20 08:54
> > I can try rolling back to the 1.8.0_72 released I had installed before, and we can see if that makes any difference.
>
> I'm also using 1.8.0_92.

ah, OK. I guess I won’t bother with trying to roll it back then.

**Comment by cvrebert** [comment] 2016-06-20 10:29
Checked some more things. It turns out the error starts occurring with 16.3.3. (I had been trying to jump directly from 16.1.1 to the latest version.)

**Comment by sideshowbarker** [comment] 2016-06-20 11:08
> Checked some more things. It turns out the error starts occurring with 16.3.3. (I had been trying to jump directly from 16.1.1 to the latest version.)

OK, FWIW, here for now is a diff of the file contents of the 16.3.3 jar vs the 16.1.1 jar:

```diff
-" Browsing zipfile /private/tmp/validator-16.1.1.jar
+" Browsing zipfile /private/tmp/validator-16.3.3.jar
 " Select a file with cursor and press ENTER

 META-INF/
@@ -78,9 +78,6 @@
 nu/validator/datatype/CdoCdcPair$State.class
 nu/validator/datatype/CdoCdcPair.class
 nu/validator/datatype/Charset.class
-nu/validator/datatype/CharsetList$1.class
-nu/validator/datatype/CharsetList$State.class
-nu/validator/datatype/CharsetList.class
 nu/validator/datatype/Circle.class
 nu/validator/datatype/ContentSecurityPolicy.class
 nu/validator/datatype/CssNumberToken.class
@@ -510,7 +507,6 @@
 nu/validator/servlet/
 nu/validator/servlet/BufferingRootNamespaceSniffer.class
 nu/validator/servlet/CharsetEmitter.class
-nu/validator/servlet/CssDetector.class
 nu/validator/servlet/DelegatingServletInputStream.class
 nu/validator/servlet/FormEmitter.class
 nu/validator/servlet/Html5ConformanceCheckerTransaction.class
```

Those are expected differences.

But of course there could be some other difference that was introduced in the contents of the class files or something else in the jar. Will look further.

**Comment by cvrebert** [comment] 2016-06-20 11:19
Looks like I'm hitting https://github.com/sbt/sbt/issues/1214
The problem only occurs under `sbt test`, not `sbt console` or IntelliJ.
Apparently the solution is to use `new ScriptEngineManager(null)` in https://github.com/validator/validator/blob/master/src/nu/validator/datatype/tools/CssParser.java#L45

**Comment by sideshowbarker** [comment] 2016-06-20 11:21
> Apparently the solution is to use `new ScriptEngineManager(null)` in https://github.com/validator/validator/blob/master/src/nu/validator/datatype/tools/CssParser.java#L45

OK, I can try making that change and rebuilding that jar (will try to get to it within the next ~90 minutes)

**Comment by sideshowbarker** [comment] 2016-06-20 11:23
> Looks like I'm hitting sbt/sbt#1214

Ah yeah because of the change I made to use Nashorn. I guess I’m now somewhat surprised that didn’t cause any other problems.

**Comment by cvrebert** [comment] 2016-06-20 11:33
By the way, is that `br.mark(1);` in `CssParser` actually necessary?

**Comment by sideshowbarker** [comment] 2016-06-20 12:44
> By the way, is that `br.mark(1);` in `CssParser` actually necessary?

Lacking any accompanying `.reset()`, almost certainly not, I guess. Unless there are some other side effects to `.mark()` that I’m unaware of.

Anyway, I removed it and I have tests which exercise that code, and the tests are passing, so I can assume that dropping it does not break anything at least.

And I’ve now committed that fix along with the change of adding the `null` arg in `ScriptEngineManager(null)`, and rebuilt the 16.6.20 jar and re-deployed it to maven central.

I’m not sure how long the update latency is once something gets pushed, so please wait a short while and then try it again and see if it fixes the issue for you.

**Comment by sideshowbarker** [comment] 2016-06-20 12:58
OK, https://repo1.maven.org/maven2/nu/validator/validator/16.6.20/validator-16.6.20.jar seems to now have the `CssParser` change, so please do give it a try. If it now works for you as expected, I’ll go ahead and actually publish the 16.6.20 release.

**Comment by cvrebert** [comment] 2016-06-21 02:10
I can confirm that the change fixes the issue as expected. 😄

**Comment by sideshowbarker** [comment] 2016-06-21 02:29
> I can confirm that the change fixes the issue as expected. 😄

Super—glad to hear it and thanks for having identified the problem and fix.

**Closed** 2016-06-21 02:33 UTC
