### ISSUE TITLE
Which validator should validator.whatwg.org link to?

### ISSUE THREAD

**Issue by foolip** [validator/validator#239] opened 2016-02-06 18:26 UTC
One of
 * https://validator.nu/
 * https://html5.validator.nu/
 * https://validator.w3.org/nu/

Which of these are the most up to date and reliable? @hsivonen, both of the validator.nu ones say "Living Validator", which is the main reason I ask, and also, should they simply be merged?

**Comment by sideshowbarker** [comment] 2016-02-21 03:55
I propose we consider making an instance of the HTML checker available at either of the following:

* `https://checker.whatwg.org/`
* `https://htmlchecker.whatwg.org/`

I prefer the first because it’s shorter but if others think it’s not precise enough (because I guess it’s imaginable there are other kinds of checkers we might provide), then let’s do the second.

For deployment, we could just set up the WHATWG Web server to proxy `https://checker.whatwg.org/` to https://sideshowbarker.net/checker/ where I have an instance of the HTML checker running that actually conforms to the HTML spec (unlike https://validator.w3.org/nu/ which follows the W3C fork).

That’s my own server and I keep that instance up to date with the source in the master branch of the repo.

Given that we already have the WHATWG web server set up to serve https://validator.whatwg.org/ then another possibility is to just (re)use that subdomain to provide an instance of the HTML checker. As it is now, that subdomain isn’t really super-useful (the information there is more suited to a wiki or something).

I’d prefer `https://checker.whatwg.org/` instead of `https://validator.whatwg.org/` because I think we need to be moving away from calling the tool a “validator” and instead call it an “HTML checker” or just a “checker”. So having the name “validator” in the URL would kind of be at odds with that.

#### Why I don’t like the term _validator_

There are a lot of reasons why I don’t like the term “validator” and I avoid using it myself. It basically has a number of unhelpful connotations: It causes people to associate things with the legacy W3C SGML/DTD-based validator, and thus causes them to also have assumptions that any other tool that calls itself a “validator” should behave  more like that legacy validator, and that it have the same purpose as that.

But this tool doesn’t have the same purpose as the legacy W3C one, and its behavior is intentionally quite different. What it comes down to is that this HTML checker is just a tool to help authors catch unintended mistakes, and intentionally not a tool for giving themselves a pat on the back for being “valid”.

For more context on the purpose, see https://sideshowbarker.net/checker/about.html#why-validate

**Comment by foolip** [comment] 2016-02-21 17:20
Setting up a new instance somewhere sounds OK, and htmlchecker.com is only $22k so if you skip eating for two years you can afford it. Kidding aside, wherever it's set up, it'd be nice if validator.nu was then redirected so that it's clear which one to use. I guess I'm not the only one who learned for a few years that validator.nu was the one and only.

**Comment by hsivonen** [comment] 2016-02-22 14:11
https://validator.nu/ and https://html5.validator.nu/ go to the exact same process, so they are equally up-to-date. Since https://validator.w3.org/nu/ follows the W3C fork, the WHATWG probably shouldn't link to that one.

Since for many, many months running, @sideshowbarker has been more active with validator development than I've been, it's safe to say that https://sideshowbarker.net/checker/ has gotten new code deployed more often than https://validator.nu/ and https://html5.validator.nu/ recently.

Rather than redirecting validator.nu, I do intend to keep it better up-to-date.

**Comment by foolip** [comment] 2016-02-23 01:44
If validator.nu were always up to date, would there still be any reason to host another instance, @sideshowbarker? Just branding, i.e. avoiding the term *validator*?

**Comment by sideshowbarker** [comment] 2016-02-23 03:19
> If validator.nu were always up to date, would there still be any reason to host another instance, @sideshowbarker? Just branding, i.e. avoiding the term *validator*?

With validator.nu being kept up to date going forward, validator.nu is the right solution to the problem we’re trying to solve—because it’s actually the tool that users already know and are already using.

What I mean is, I think the only important issue there’s been with validator.nu is just that it hasn’t always remained as up to date, and so it wasn’t solving the original problem we want to solve.

And to be clear on what I understand as the original problem we wanted to solve: It’s two requirements:

1. We need a conformance-checker service we can point users to that we can rely on being up to date with the current HTML spec (and one that we can use ourselves for our own CI and such).
2. The tool we use and refer users to must follow the HTML spec instead of the W3C fork.

validator.nu has not been meeting requirement 1 as closely as we’d like, but that issue is being resolved, so we will have both requirements met and no longer have a problem.

That said, I think there’s still value in having a secondary instance along with validator.nu, for two reasons:

1. Occasionally validator.nu goes down, so it’s helpful to have a backup to use and refer people to.
2. I sometimes push changes to the sources very often—even multiple times in a day—and sometimes introduce transient regressions and flubs that can destabilize the behavior for users. So it makes some sense for validator.nu to not always be absolutely up-to-the-minute in sync with the sources.

So I can imagine that along with having validator.nu as the up-to-date (relatively) production instance, we have a second instance that’s the bleeding-edge development instance reflecting the current repo state.

So if validator.nu gets updated, say, roughly once a week, then I think that would be up to date enough. And anybody wanting to use and test with the absolutely latest will have the dev instance to do that with.

About the name, it’s true I’m not fond of the term _validator_ these days, but that’s a relatively unimportant pet peeve compared to other concerns (and the project is hosted https://github.com/validator/validator so we’d have challenge trying to eradicate the _validator_ term everywhere anyway).

**Comment by foolip** [comment] 2016-02-23 03:32
Maybe you can work out a scheme to automatically deploy on validator.nu every Sunday or something? And then you can make risky changes on Mondays so that you have time to fix them before the next roll?

**Comment by hsivonen** [comment] 2016-02-23 09:20
Validator.nu is now up-to-date. I finally migrated it to a new server that has OpenJDK 8, so I was able to push the latest changes (that changed javac to target JDK 8).

Weekly updates are unlikely to happen in the next 3 weeks, but after that, let's resolve the validator.nu updating problem and the watchdog problem. (If I'm lucky, maybe I can resolve the watchdog problem later today.)

**Comment by foolip** [comment] 2016-02-23 09:46
What is the watchdog problem?

**Comment by foolip** [comment] 2016-02-23 09:49
Is validator.nu now following WHATWG HTML and not W3C? "Using the schema for HTML5 + SVG 1.1 + MathML 3.0 + RDFa Lite 1.1" makes me a bit suspicious, but then https://sideshowbarker.net/checker/ says the same thing.

**Comment by sideshowbarker** [comment] 2016-02-23 10:52
> Validator.nu is now up-to-date. I finally migrated it to a new server that has OpenJDK 8, so I was able to push the latest changes (that changed javac to target JDK 8).
> 
> Automated weekly updates are unlikely to happen in the next 3 weeks, but after that, let's resolve the validator.nu updating problem and the watchdog problem. (If I'm lucky, maybe I can resolve the watchdog problem later today.)

Thanks much—all great to hear

And sorry for having complicated things by introducing the OpenJDK 8 requirement recently (I blame it on CSP—since the reason I introduced it was a consequence of adding support for CSP syntax checking.)

**Comment by sideshowbarker** [comment] 2016-02-23 10:54
> What is the watchdog problem?

I think Henri just meant the problem of validator.nu occasionally going down but him not yet having something set up to notify him when that happens (or to automatically restart it maybe)

**Comment by foolip** [comment] 2016-02-23 10:56
I can recommend Pingdom for uptime monitoring.

**Comment by sideshowbarker** [comment] 2016-02-23 10:58
> Is validator.nu now following WHATWG HTML and not W3C?

No, it’s definitely following WHATWG HTML

> "Using the schema for HTML5 + SVG 1.1 + MathML 3.0 + RDFa Lite 1.1" makes me a bit suspicious, but then https://sideshowbarker.net/checker/ says the same thing.

Yeah, that’s expected. We have RDFa Lite 1.1 support mostly because otherwise errors would be reported for all the Facebook opengraph stuff, and for schema.org markup. But it doesn’t support full RDFa—just the Lite subset (same as what schema.org follows).

If your point is that Microdata isn’t explicitly mentioned there, it’s intentionally not to—the reason being that Microdata is a normative part of the HTML language itself (unlike RDFa), and fully defined in the HTML spec itself.

**Comment by foolip** [comment] 2016-02-23 11:01
No, I mean rather that "HTML5" and "RDFa Lite 1.1" both sound very W3C-like, but I guess this message is the same regardless of the "follow W3C" setting?

**Comment by sideshowbarker** [comment] 2016-02-23 19:30
> No, I mean rather that "HTML5" and "RDFa Lite 1.1" both sound very W3C-like, but I guess this message is the same regardless of the "follow W3C" setting?

Yes, it’s the same regardless of the "follow W3C" setting. And the reason it’s emitted is that the validator.nu UI provides a way to choose among a set of preset schemas in particular combinations. So that info message is there to indicate to the user which set of schemas they’ve selected.

And the version numbers (_HTML5_ instead of _HTML_, _SVG 1.1_ instead of _SVG_) are included because in the past at least we had thought it was important to make clear to users what spec version we check against.

But https://html5.validator.nu/ and https://sideshowbarker.net/checker/ both just use a default schema that’s the combination of HTML+SVG+MathML+RDFaLite—so, arguably, that info message detailing which schemas and versions were used is not useful in that context (and is a waste of bandwidth).

So I think maybe I’ll try making a change that just suppresses that info message for the https://html5.validator.nu/ and https://sideshowbarker.net/checker/ case.

Dropping that message would also better align with the purpose of it as a checker (to catch mistakes) rather than a validator. And in that context it’s much less important (or even totally non-important) for the UI to explicitly tell users every single time which specs/versions it’s checking against—because that kinda reinforces the misconception of the purpose being to make claims of validity to particular specs.

So instead of putting that message into the UI, we could just put the details in the _about_ page for the tool, for those who want to know it—though IMHO most users probably don’t care to know, because they are (rightly) using it just to catch their won mistakes and not to evaluate conformance _per se._

**Comment by sideshowbarker** [comment] 2016-02-27 18:36
> Is validator.nu now following WHATWG HTML and not W3C? "Using the schema for HTML5 + SVG 1.1 + MathML 3.0 + RDFa Lite 1.1" makes me a bit suspicious… "HTML5" and "RDFa Lite 1.1" both sound very W3C-like,

I’ve changed all occurrences of `HTML5` to just `HTML` in any messages emitted by the checker and in all parts of the checker UI.

Also, `Using the schema for HTML5 + SVG 1.1 + MathML 3.0 + RDFa Lite 1.1` is no longer shown as an info message but instead in the https://validator.nu/ UI is just included in the final success/failure message after all the actual errors/warnings (if any), and in the https://checker.html5.org/ UI is no longer shown at all (not even in the final success/failure message).

**Comment by foolip** [comment] 2016-02-27 18:57
Nice!

**Comment by sideshowbarker** [comment] 2016-03-01 18:49
Closing this as we now have https://checker.html5.org/ being kept up to date with the source from master here, and https://html5.validator.nu/ will also be getting updated more often now.

**Closed by sideshowbarker** 2016-03-01 18:49 UTC

**Comment by foolip** [comment] 2016-03-02 11:15
Thanks for clearing this up!

**Comment by hsivonen** [comment] 2016-03-06 13:03
> What is the watchdog problem?

The validator crashes from time to time. Previously, this required manual intervention. I now have a watchdog (simple enough that I should have done this ages ago) that restarts the validator after a crash. (The upgrade to JDK 8 really forced the watchdog issue. With JDK 7 / older validator code, the validator went on months without crashing, but with JDK 8 / up-to-date validator code, it can crash several times per day.)

This still causes an interruption in service, which isn't cool, so I will need to figure out how to make it not crash (if that's actually feasible given user-controlled inputs and finite memory).

(And the deployment is indeed up-to-date as of today.)

**Comment by sideshowbarker** [comment] 2016-03-07 03:31
> With JDK 7 / older validator code, the validator went on months without crashing, but with JDK 8 / up-to-date validator code, it can crash several times per day.

Have you been able to narrow down at all what’s causing it to crash? Memory issues, or load, or something else altogether?

I’ve been running five instances of the backend for several years for the W3C service, and in that time I have never seen any instance crash even once.

Granted, they’re running on pretty beefy hardware (ProLiant DL360 G5, 16GB RAM, 3.3GHz, 8 cores). But I never see the memory usage of any of the instances rise above a few hundred megabytes, and each of them is handling 3 to 5 requests every second without any problems.

And although we switched all the systems over to Java8 only relatively recently—in the last 3 months or so I think—I haven’t noticed any differences. Certainly it’s still the case that none have ever crashed.
