### ISSUE TITLE
probably error in interpreting mailto: links & vs. &amp

### ISSUE THREAD

**Issue by eppich** [validator/validator#172] opened 2015-10-10 18:34 UTC
Hi everybody,

i wondered, if it is correct, that an "&" inside a link like "...&Subject=blabla" causes the following error:

"& did not start a character reference. (& probably should have been escaped as &amp;.)"

Is this a potential a bug of the validtator? My site: http://www.sonnenlandimmobilien.de
Validator-Link: https://validator.w3.org/nu/?doc=http%3A%2F%2Fwww.sonnenlandimmobilien.de%2F&showsource=yes

Greetings
Peter

**Comment by cvrebert** [comment] 2015-10-10 19:09
Duplicate of #31 ?

**Comment by sideshowbarker** [comment] 2015-12-12 02:40
> Duplicate of #31 ?

Yeah. the checker is not conforming to the current requirements in the HTML spec on this; it’s a known issue but it is outside of my ability to fix on my own, because it requires a change to the HTML parser we’re using, and I’ve not yet been successful in getting my patch with the fix accepted.

@eppich The workaround is to make sure to write all you `&` out as `&amp;`. To browsers, those two are the same thing, so using `&amp;` is not going to break the links.

I’m going to go ahead and close this out but if you have further comments or questions, feel free to continue to post here, and/or re-open the issue if you disagree with the resolution.

**Closed by sideshowbarker** 2015-12-12 02:40 UTC

**Comment by sideshowbarker** [comment] 2016-01-02 10:14
Fixed in v16.1.1 and after https://github.com/validator/validator/releases/latest and pushed to https://validator.w3.org/nu/
