### ISSUE TITLE
Validator adds non existing artefacts around css style id class

### ISSUE THREAD

**Issue by pl752** [validator/validator#1652] opened 2023-10-15 13:28 UTC
Content:
```html
<!DOCTYPE html>
<html lang="ru">
	<head>
		<title>Позиционирование</title>
		<style>
		#leftcol {
			position: relative;
			float: left;
			width: 400px;
			color: white;
			background: #800000;
		}
		#rightcol {
			position: relative;
			float: left;
			left: -50px;
			top: 50px;
			width: 120px;
			background: #e0e0e0;
			border: solid 1px black;
		}
		#leftcol P {
			padding: 10px;
			padding-right: 50px;
			margin 0;
		}
		#rightcol P {
			padding: 10px;
			padding-top: 0;
		}
		</style>
	</head>
	<body>
		<div id="leftcol"><p>
		Кроме использования параметра float для размещения рядом по горизонтали двух и более
		слоев, для этой же цели применяется и параметр position.
		Позиционирование слоев предполагает использование стилевого параметра position, который
		задает, относительно каких координат ведется положение слоя. Для аргумента absolute за основу
		берется родительский элемент или окно браузера, относительно границ которого и указывается, где
		должен располагаться слой на веб-странице. Аргумент relative задает смещение слоя относительно его
		исходного расположения.
		</p></div>
		<div id="rightcol"><p>
		Причем можно управлять процессом наложения слоев друг на друга,
		получая таким образом интересные дизайнерские эффекты.
		</p></div>
	</body>
</html>
```
Detected language: 
`
#leftcol P {
			padding: 10px;
			padding-right: 50px;
			margin 0;		}		#rightcol P {				}
		#rightcol P {
			padding: 10px;
			padding-top: 0;
		}
`
For some reason validator adds non existing artefacts around rightcol id class in style block, these aren't present in original code, and says "margin css parse error".

**Comment by sideshowbarker** [comment] 2023-10-15 13:47
hmm yeah that’s a bug — but at this point I don’t have any idea what the cause might be

**Comment by pl752** [comment] 2023-10-15 14:16
there is typo after margin, : is omitted, but behaviour is still strange

**Comment by sideshowbarker** [comment] 2023-10-15 14:47
Ah yeah, if that typo is corrected, then the checker reports no errors.

And given that the checker is reporting the correct line where the typo is, and “CSS: `margin`: Parse Error” that clearly indicates the part with the `margin` property is where the typo is, then there’s no bug in the checker at least, so I’m going ahead and closing this.

**Closed by sideshowbarker** 2023-10-15 14:47 UTC

**Comment by pl752** [comment] 2023-10-15 15:08
Yes, error message is valid, the fact that validator is modifying provided text is strange
