### ISSUE TITLE
Publish new release on Maven-Central

### ISSUE THREAD

**Issue by fabian-froehlich** [validator/validator#1464] opened 2022-10-27 07:08 UTC
With the current Version on Maven-Central `20.7.2` it is possible to include a html-validator into our application. 
But since its release is from 2020 it contains outdated dependencies with critical CVE's.
Is there a reason, that there was no further release of the library?
We would be glad if there was an ongoing release cycle.

**Comment by rdeltour** [comment] 2022-10-27 08:37
seems to be a duplicate of #1354

**Comment by fabian-froehlich** [comment] 2022-10-27 09:53
Yes, I also saw your post. But it did not have any recent activities.

**Comment by sideshowbarker** [comment] 2022-10-29 04:48
Closing in favor of https://github.com/validator/validator/issues/1354

**Closed by sideshowbarker** 2022-10-29 04:48 UTC
