### ISSUE TITLE
Disagree - Misuse of aria-label attribute

### ISSUE THREAD

**Issue by hnotavio** [validator/validator#1131] opened 2021-04-05 21:10 UTC
Good afternoon. I'm a developer at Claro Brasil.
During validation of my code in production, I came across an error saying that there is misuse of aria-label in a div

This is the following code:

```html
<div class = "mdn-Accordion-box" aria-label = "Clickable agreement to expand content">
```

Taking into account the definitions of the aria-label, I don't see the reason for the error.
It is serving for vocalizers to inform the blind user about a specific area of the page and to advise them on what to do. That is, it is an instruction code, tested by blind users.

Thanks

**Comment by cvrebert** [comment] 2021-04-05 21:44
You need to put the HTML within backticks in GitHub, so we can see the code. Otherwise Markdown renders it literally (or strips it out in many cases).

**Comment by scottaohara** [comment] 2021-04-05 21:55
If your div is without an explicit role that allows naming, then this would be a duplicate of https://github.com/validator/validator/issues/1090

**Comment by sideshowbarker** [comment] 2021-04-09 10:46
Closing per https://github.com/validator/validator/issues/1131#issuecomment-813673090

**Closed by sideshowbarker** 2021-04-09 10:46 UTC
