### ISSUE TITLE
 HTML checker has misidentified the language

### ISSUE THREAD

**Issue by pedroborregoinmediatamente** [validator/validator#406] opened 2016-11-14 16:25 UTC
the validator responds with an error 

>  This document appears to be written in English but the html start tag has lang="it". Consider using lang="en" (or variant) instead.

even when page is actually in italian language, this is not happening with all pages but just one for now (still validating a few more before finishing the entire site).

**Comment by cvrebert** [comment] 2016-11-14 16:44
We need either a link to or the HTML of the misidentified webpage in order to investigate the problem.

**Comment by pedroborregoinmediatamente** [comment] 2016-11-14 16:55
[missidentified it language.txt](https://github.com/validator/validator/files/589899/missidentified.it.language.txt)

there you go I hope that helps.

**Comment by zcorpan** [comment] 2016-11-21 12:16
I think it's because there is HTML in the `textarea`s (with URLs containing English-looking strings, and `width='1' height='1'`).

**Comment by sideshowbarker** [comment] 2016-12-11 08:42
> I think it's because there is HTML in the `textarea`s (with URLs containing English-looking strings, and `width='1' height='1'`).

The language detector should already be ignoring all the `textarea`s in that doc, because they’re inside a `form` in that doc, and the language detector already ignores everything inside `form`s.

**Comment by sideshowbarker** [comment] 2016-12-11 09:14
@pedroborregoinmediatamente I can’t reproduce this currently with https://validator.w3.org/nu/. ( I made some changes recently that may have fixed it.) Please let me know if you can still reproduce it, and I’ll investigate further.

**Comment by pedroborregoinmediatamente** [comment] 2016-12-12 14:09
Thank you Sr. Effectively It does not reproduces the language tag warning any more.

**Comment by sideshowbarker** [comment] 2016-12-12 15:01
@pedroborregoinmediatamente OK thanks I’ll go ahead and close this, then. But if you run problems with other documents please do raise issues here

**Closed by sideshowbarker** 2016-12-12 15:01 UTC
Labels: known issue

**Comment by pedroborregoinmediatamente** [comment] 2016-12-13 08:22
Good enough for me, thanks!
