### ISSUE TITLE
The checker crashes if there is an img tag in the head

### ISSUE THREAD

**Issue by kefilev** [validator/validator#745] opened 2019-01-18 08:47 UTC
The checker crashes if there is an img tag in the head section and doesn't show the rest of the errors after this. 

Having img tag of course is an error, but Facebook pixel tracking code has img tag in it and you should place it in the head of the document. So in order to see all the errors I need to disable Facebook tracking for a moment, check the page and enable it after that.

**Comment by sideshowbarker** [comment] 2019-01-18 09:05
Please provide a test document or URL that demonstrates the problem.

It can’t be reproduced just by putting an img element in the head; look here:

https://validator.w3.org/nu/?showsource=yes&doc=data%3Atext%2Fhtml%3Bcharset%3Dutf-8%2C%253C%2521DOCTYPE%2520html%253E%250D%250A%253Chtml%2520lang%253D%2522%2522%253E%250D%250A%253Chead%253E%250D%250A%253Ctitle%253ETest%253C%252Ftitle%253E%250D%250A%253Cimg%2520src%253Dfoo%2520alt%253Dbar%253E%250D%250A%253C%252Fhead%253E%250D%250A%253Cbody%253E%253C%252Fbody%253E%250D%250A%253C%252Fhtml%253E#textarea

**Comment by kefilev** [comment] 2019-01-18 09:13
Hello, 
Actually you reproduced the problem. As you can see in the results there are 2 errors. But actually there are no errors in this test document, except the img tag in the head.     On Friday, January 18, 2019, 11:05:25 AM GMT+2, Michael[tm] Smith <notifications@github.com> wrote:  
 
 
Please provide a test document or URL that demonstrates the problem.

It can’t be reproduced just by putting an img element in the head; look here:

https://validator.w3.org/nu/?showsource=yes&doc=data%3Atext%2Fhtml%3Bcharset%3Dutf-8%2C%253C%2521DOCTYPE%2520html%253E%250D%250A%253Chtml%2520lang%253D%2522%2522%253E%250D%250A%253Chead%253E%250D%250A%253Ctitle%253ETest%253C%252Ftitle%253E%250D%250A%253Cimg%2520src%253Dfoo%2520alt%253Dbar%253E%250D%250A%253C%252Fhead%253E%250D%250A%253Cbody%253E%253C%252Fbody%253E%250D%250A%253C%252Fhtml%253E#textarea

**Comment by sideshowbarker** [comment] 2019-01-18 10:00
The checker is behaving correctly. When you put an `<img>` tag inside the head element in the markup source for a document, the HTML parser essentially inserts a `</head>` end tag and a `<body>` start tag before the `<img>` element. So given the following markup source:

```html
<!DOCTYPE html>
<html lang="">
<head>
<title>Test</title>
<img src=foo alt=bar>
</head>
<body></body>
</html>
```

… that markup source is equivalent to the following markup source:

```html
<!DOCTYPE html>
<html lang="">
<head>
<title>Test</title>
</head>
<body>
<img src=foo alt=bar>
</head>
<body></body>
</html>
```

That’s basically how the parser sees it — and so that’s why the checker reports two errors:

* *“Stray end tag head”* — because in the parsed document there’s essentially already a `</head>` end tag before the img element, so the head element isn’t open any long (so the parser drops the stray `</head>` tag and reports the error) 
* *“Start tag `body` seen but an element of the same type was already open”* — because in the parsed document, there’s essentially already a `<body>` start tag before the img element, so the body element is already open (so the parser drops the stray `<body>` start tag and reports the error)

If you want to confirm the parser behavior on your own, open the document in browser devtools and use the DOM inspector to view the parsed document; what you’ll find is that the img element ends up in the body, not in the head.

**Comment by LeeKowalkowski** [comment] 2019-01-18 10:36
Facebook's advice at https://github.com/validator/validator/issues/745 https://www.facebook.com/business/help/952192354843755 is the problem, really.

There's no benefit to putting the code before `</head>` instead of after `<body>`.   Personally I would put tracking code right down the page before `</body>` because it's just not meaningful to track page views if the complete HTML was not parsed - this user probably didn't view your page.

**Comment by sideshowbarker** [comment] 2019-01-22 09:07
Closing per https://github.com/validator/validator/issues/745#issuecomment-455491849 but feel free to comment here if any further information is needed.

**Closed by sideshowbarker** 2019-01-22 09:07 UTC
Labels: not a bug
