### ISSUE TITLE
'Writing-mode: tb-lr' should not break the validation

### ISSUE THREAD

**Issue by FrankConijn** [validator/validator#778] opened 2019-03-30 10:58 UTC
The table on https://newskiinstruction.com/actions-table.php does not pass the validation because "CSS: `writing-mode: tb-lr` is not a `writing-mode` value." Strictly speaking that may be so (it has been replaced with `writing-mode: vertical-lr`), but it is the only value IE11 renders. And all other major browsers render both, so they have no problem with `tb-lr`.

**Comment by sideshowbarker** [comment] 2019-04-02 07:01
The checker is behaving as designed here. It’s the responsibility of the checker to report errors for any case that the relevant spec defines as non-conforming. And the spec for `writing-mode` is here:

https://drafts.csswg.org/css-writing-modes-3/#block-flow
https://drafts.csswg.org/css-writing-modes-4/#block-flow

So there is no spec which defines `tb-lr` as a conforming value for `writing-mode`. It’s therefore necessary for the checker to report `tb-lr` as an error.

All that said, this shouldn’t be seen as something that “breaks validation”. The intent of checker is to alert web developers/authors to unintended mistakes in the markup that they otherwise might not be aware of. If you’re instead intentionally using `tb-lr`, then you can safely ignore the error message from the checker. In that sense, all messages from the checker a just advisory.

But if you want to make the checker stop reporting a message to you for that case, you can make it do that by using the **Message Filtering** button the checker UI or by using any of the checker’s other message-filtering options; see the documentation here:

https://github.com/validator/validator/wiki/Message-filtering

**Comment by FrankConijn** [comment] 2019-04-02 18:04
I use code validation also as a selling point; I point potential customers to your site to have their site checked. So I cannot just ignore a validation error. However, I just found out that `-ms-writing-mode: tb-lr` does validate and makes IE11 behave as desired. So my problem is solved.

**Comment by sideshowbarker** [comment] 2019-04-13 10:10
Closing per https://github.com/validator/validator/issues/778#issuecomment-479124148

**Closed by sideshowbarker** 2019-04-13 10:10 UTC
