### ISSUE TITLE
Add Support for TLS 1.1 and 1.2

### ISSUE THREAD

**Issue by jerheff** [validator/validator#22] opened 2015-01-05 20:47 UTC
The validator currently fails for sites with only TLS 1.1 and 1.2 enabled.

It reports this error:
IO Error: Remote host closed connection during handshake

**Comment by sideshowbarker** [comment] 2015-01-06 02:58
Thanks for the report. Can you please post the URL for a document which produces that error? And to be clear, you mean a server that has TLS 1.0 support disabled? (And only TLS 1.1 & 1.2 support enabled.) And which validator are you testing with? https://validator.nu/ or https://html5.validator.nu/ or http://validator.w3.org/nu/ or can you reproduce this error with any of them.

**Comment by sideshowbarker** [comment] 2015-01-08 07:07
Thanks—will investigate. I think (hope) it might be possible to fix it just be embedding a newer version of jetty

**Comment by sideshowbarker** [comment] 2015-01-08 07:08
Stack traces https://gist.github.com/sideshowbarker/21fc8a22ad3cad41eb74 https://gist.github.com/sideshowbarker/7fd83a3791f4702c2402

**Comment by hsivonen** [comment] 2015-01-08 10:16
This is about outbound TLS, so it's not about Jetty. (Besides, the deployment at https://html5.validator.nu terminates inbound TLS in nginx, so Jetty doesn't do any TLS at all.)

The current deployments are on OpenJDK 7. We need to move the deployments to OpenJDK 8 to get modern outbound TLS.

Additionally, somewhat on-topic and somewhat off: We currently use a legacy version of Apache HttpClient, which doesn't set SNI. The problem with updating HttpClient is that its developers keep redesigning the APIs, so updating involves writing to a new API at our end. It might be possible to hack around the SNI problem without upgrading HttpClient, though. In any case, I'll dig up my WIP patch from old Merquerial queue and publish it as a git branch, hopefully in the coming days.

**Comment by sideshowbarker** [comment] 2015-01-08 10:32
> The current deployments are on OpenJDK 7. We need to move the deployments to OpenJDK 8 to get modern outbound TLS.

OK, fwiw I can say that's doable for the w3c instances. We already have OpenJDK installed on the hosts, so I think it'd just amount to me changing JAVA_HOME in the environment of the run scripts for the instances.

But I'd rather not do that until you're also ready to redeploy the validator.nu and html5.validator.nu instances.

And anyway for all instances I guess it should wait until the SNI support has landed too.

**Comment by sideshowbarker** [comment] 2015-02-09 02:44
This weekend for other reasons I went ahead and updated the W3C validator backend environment to Java 8. That still doesn't get us SNI support but it does address the problem originally reported here, in that http://validator.w3.org/nu/?doc=https%3A%2F%2Fus.hunchlab.com%2F should now give you validation results instead of just falling during the TLS handshake.

And since the solution for the problem originally reported here is a deployment-environment issue and not an issue that can be fixed in the validator code itself, I'm gonna go ahead and close this issue out. But feel free to reopen it if you run into any other problems with it now.

**Closed by sideshowbarker** 2015-02-09 02:44 UTC
