### ISSUE TITLE
FTBFS on IA64

### ISSUE THREAD

**Issue by wom-bat** [validator/validator#34] opened 2015-02-13 23:25 UTC
Using openjdk-6-jdk I do:
  export JAVA_HOME=/usr//lib/jvm/java-6-openjdk-ia64/
  python ./build/build.py all

and see
        [jar] Building jar: /usr/src/validator/jing-trang/build/trang.jar
jar:

BUILD SUCCESSFUL
Total time: 18 seconds
The system is out of resources.
Consult the following stack trace for details.
java.lang.StackOverflowError
        at com.sun.tools.javac.tree.JCTree$JCBinary.accept(JCTree.java:1539)
        at com.sun.tools.javac.jvm.Gen.genExpr(Gen.java:832)
        at com.sun.tools.javac.jvm.Gen.genCond(Gen.java:812)
        at com.sun.tools.javac.jvm.Gen.genCond(Gen.java:765)
...

Stack size is limited to 8M on this system which has 8G of RAM.
There is nothing in the system logs to suggest a problem.

**Comment by sideshowbarker** [comment] 2015-02-14 02:55
Are you building from the latest sources? I ask because until recently we had a stack size hardcoded into  the runtime args for the validator, but I just changed that about a week ago:

https://github.com/validator/validator/commit/ef79508cbe7da61eba0870bca069e6c2265920a2

So if you build from the latest sources now, by default the validator will just run with the default Java stack size for 64-bit VMs—which I think is 1024MB—and it should work fine. However, I also added a new `--stacksize=NNNN` option you can give to the build script to tune the stack size if necessary.

But if you can't build from the latest sources for some reason, please try changing the hardcoded  `-Xss512k` and  `-XX:ThreadStackSize=2048` lines in the `build/build.py` script to adjust the stack size.

I think the problem you're seeing might be because the 512KB stack size we previously had hardcoded is not big enough for 64-bit VMs. The validator build requires more than that but doesn't more 1024KB, so I am pretty sure at least it's not running into that 8M limit in your environment.

**Comment by wom-bat** [comment] 2015-02-14 04:03
I'm using the latest revision, at e7f782814aa6f33402b45c7c1ac5f2520850748b which was committed today.

This builds OK on AMD64.  But not on IA64.  I'm beginning to suspect a jdk bug, as it's javac that's dying.

**Comment by sideshowbarker** [comment] 2015-02-14 05:21
ah yeah the validator code related to the stack-size setting only affects the runtime behavior of the validator and not the actual build, and I realize from re-reading your bug report now that the problem you reported is happening during the build and not at run time.

I'll try to find an IA64 environment to test in but to test the possibility that it's not strictly a javac bug but instead really is caused by the build consuming more resources than the default javac settings, can you maybe try tweaking the build script with something similar to the following change:

```
diff --git a/build/build.py b/build/build.py
index d2878cc..363f02f 100755
--- a/build/build.py
+++ b/build/build.py
@@ -249,7 +249,7 @@ def runJavac(sourceDir, classDir, classPath):
   if javaVersion != "":
     args.append('-target ' + javaVersion)
     args.append('-source ' + javaVersion)
-  runCmd('"%s" %s %s' % (javacCmd, " ".join(args), '@temp-javac-list'))
+  runCmd('"%s" -J-Xms512m -J-Xmx1024m -J-Xss1024k -J-XX:MaxPermSize=384m %s %s' % (javacCmd, " ".join(args), '@temp-javac-list'))
   removeIfExists("temp-javac-list")
 
 def copyFiles(sourceDir, classDir):

```

**Comment by sideshowbarker** [comment] 2015-02-14 05:49
If the problem is in the build of the jing-trang code (I think it's not—otherwise you'd not be seeing the `BUILD SUCCESSFUL` message—but just in case…) the change I suggested at https://github.com/validator/validator/issues/34#issuecomment-74362518 isn't going to affect it, but something like the following might.

```
diff --git a/build.xsl b/build.xsl
index 62f7e68..6188323 100644
--- a/build.xsl
+++ b/build.xsl
@@ -81,8 +81,9 @@
     </xsl:attribute>
     <mkdir dir="{$build}/mod/{$name}/classes/main"/>
     <xsl:if test="compile">
-      <javac destdir="{$build}/mod/{$name}/classes/main">
+      <javac fork="true" destdir="{$build}/mod/{$name}/classes/main">
        <xsl:call-template name="javac-attributes"/>
+       <compilerarg line="-J-Xms512m -J-Xmx1024m -J-Xss1024k -J-XX:MaxPermSize=384m" />
        <src>
          <pathelement location="mod/{$name}/src/main"/>
          <xsl:if test="ant/@precompile">
@@ -120,8 +121,9 @@
     </xsl:attribute>
     <mkdir dir="{$build}/mod/{$name}/classes/test"/>
     <xsl:if test="compile[@test]">
-      <javac destdir="{$build}/mod/{$name}/classes/test">
+      <javac fork="true" destdir="{$build}/mod/{$name}/classes/test">
        <xsl:call-template name="javac-attributes"/>
+       <compilerarg line="-J-Xms512m -J-Xmx1024m -J-Xss1024k -J-XX:MaxPermSize=384m" />
        <src>
          <pathelement location="mod/{$name}/src/test"/>
        </src>

```

**Comment by wom-bat** [comment] 2015-02-14 10:12
None of this helps (but thankyou!)
I ended up compiling on another machine, and just deploying vnu.jar.  FWIW, it seems to need 3000k as stack to start up (1024k gives an out-of-stack exception when parsing the schemas)

**Comment by sideshowbarker** [comment] 2015-02-14 17:28
> I ended up compiling on another machine, and just deploying vnu.jar.

OK, that works too :-)

> FWIW, it seems to need 3000k as stack to start up (1024k gives an out-of-stack exception when parsing the schemas)

Yeah, that step is the only place where I've ever seen it run into the stack constraints. But on every other architecture I've ever tested on it's never needed stack anywhere close to 3000k. So it'd be interesting to understand why there's a difference. I'll look around more to see if we might have an IA64 machine somewhere among the W3C systems that I can test on.

**Comment by sideshowbarker** [comment] 2015-02-16 06:06
So I've not had any success in finding an IA64 environment to troubleshoot this in myself—and given the age of Java6 and support status for from Sun, etc., fixing Java6-specific issues in the validator isn't a high priority. So I'm going to go ahead and close this. But if you can reproduce in this in a Java7 or Java8 IA64 environment or if you end up running into other problem behavior with the validator building/running on IA64, please do take time to report it here.

**Closed by sideshowbarker** 2015-02-16 06:06 UTC
Labels: known issue
