### ISSUE TITLE
Media not allowed on meta at this point

### ISSUE THREAD

**Issue by abbott567** [validator/validator#1424] opened 2022-09-20 14:19 UTC
The `media` attribute is listed in the spec under the [`<meta>`](https://html.spec.whatwg.org/multipage/semantics.html#the-meta-element) tag, and is even listed in the output of the W3C error message as a valid attribute.

URL being validated or code to reproduce error: https://www.craigabbott.co.uk

```
Error: Attribute media not allowed on element meta at this point.

From line 16, column 5; to line 16, column 85
 
9f9">↩    <meta name="theme-color" media="(prefers-color-scheme: light)" content="#f9f9f9">↩    <

Attributes for element meta:
    Global attributes
    name — Metadata name
    http-equiv — Pragma directive
    content — Value of the element
    charset — Character encoding declaration
    media — Applicable media
```

**Comment by jfrech** [comment] 2022-10-15 16:36
Duplicate of #1166. VTC

**Closed** 2022-10-27 05:49 UTC
