### ISSUE TITLE
Element style not allowed as child of element div in this context

### ISSUE THREAD

**Issue by samiahmedsiddiqui** [validator/validator#725] opened 2018-11-06 11:29 UTC
style element contents got validated in `24 March 2018` release. 
[https://github.com/validator/validator/releases/tag/18.3.0](https://github.com/validator/validator/releases/tag/18.3.0)

`
the second is a (non-optional) feature to check that style element contents and style attribute values in HTML documents are valid CSS.
`

After your March release, i have added the CSS in body and it's all valid till Friday `2 Nov 2018` but suddenly it starts throwing error. I have checked and found that you guys have released the some updates on `05 Nov 2018` that may causing it. Can you please check this out:
[https://validator.w3.org/nu/?showsource=yes&doc=https%3A%2F%2Fzerocater.com](https://validator.w3.org/nu/?showsource=yes&doc=https%3A%2F%2Fzerocater.com)

As i have not changed anything on my site from Friday so, i am sure that this issue belongs to your new release.

**Comment by sideshowbarker** [comment] 2018-11-06 11:35
Until yesterday https://validator.w3.org/nu/ previously checked documents using the rules in the https://www.w3.org/TR/html5/ spec, which allows the `style` element as a `body` descendant.

But https://validator.w3.org/nu/ now checks documents using the rules in the https://html.spec.whatwg.org/ spec, which does not allow `style` as a `body` descendant.

That change which spec https://validator.w3.org/nu/ uses is something that follows from a W3C decision to converge on a single normative spec, and https://html.spec.whatwg.org/ is that spec.

**Comment by BrainScanMedia** [comment] 2018-11-07 20:10
I'm getting this now on all websites...

"*_Error: Element style not allowed as child of element div in this context._*"

When I put style in body I get the error saying style not allowed in body. This is def a bug because if this is a new rule its ridiculous. We need to use styles trhoughout certain pages.

**Comment by sideshowbarker** [comment] 2018-11-08 01:37
Closing per https://github.com/validator/validator/issues/725#issuecomment-436222906 as the checker is behaving as intended.

The checker is following the requirements in the HTML spec on this. So if anybody who comes across this issue actually wants to understand the rationale for the spec requirements, take some time to read the discussion at https://github.com/whatwg/html/issues/1605

**Closed by sideshowbarker** 2018-11-08 01:37 UTC
Labels: not a bug
