### ISSUE TITLE
Detection of syntactic errors: missing </li> tag

### ISSUE THREAD

**Issue by ChrisBocay** [validator/validator#1611] opened 2023-07-16 23:47 UTC
Hello friends,

I was under the impression that the W3C validator would catch all basic HTML syntax errors. So I was surprised to see that, when I manually removed an "/li" end tag from my code just for fun, the validator did NOT report it.

I have left this (undetected) syntax error in the code on this page: https://chrisbocay.com/turn-thy-cheek-ignoring-negative-experiences-for-quicker-manifestations/

This error can easiest be located by searching for the string "link to book", when looking in the source code for the live page in any browser. You will find two instances of "link to book": the first instance has a proper "/li" end tag appended to it, while the second does NOT have it.

So my suggestion is simple. Please make the W3C validator catch *all* missing HTML end tags, including "/li" end tags.

NOTE 1: The missing "/li" end tag will, for your testing pleasure, remain until 15 August 2023, 23:59 CET. After that, I will append that missing tag myself. I would also be grateful if the software engineer who is in charge of this issue would confirm that the testing is finished and that there is no longer any need to use the test page. Hopefully, then, I would not have to wait until mid-August to reinstate it to its former glory... :)

NOTE 2: All warnings and errors reported by the W3C validator on this page are due to WordPress.com's own Blank Canvas theme code (by Automattic). It is thus NOT produced by my own HTML code that I am using within the core article portion of this page.

Hoping y'all are having a GREAT day!
Chris Bocay
https://chrisbocay.com/

**Comment by nschonni** [comment] 2023-07-17 00:42
(Almost) Duplicate of https://github.com/validator/validator/issues/1310
`<li>` is a self closing tag

**Closed by nschonni** 2023-07-17 00:42 UTC
Labels: enhancement

**Comment by ChrisBocay** [comment] 2023-07-17 09:39
Hello Nick!

Thanks for your speedy processing of this issue! It is much appreciated!

You say that "li" is a self-closing tag. But what I can see, that is not an entirely correct statement. Sure, it may be considered "optional" in many cases, according to the 2014 spec (https://www.w3.org/TR/2014/REC-html5-20141028/syntax.html#optional-tags). However, there are still situations in which it is NOT self-closing, and where a "parse error" should be issued.

In any case, a missing "li" end tag is a VERY bad practice, even though the 2014 spec (and its authors) may consider it "optional". In other words, "optional" isn't a synonym for "best practice".

Therefore, I would suggest that the W3C validator takes this into consideration, so that it can actually help HTML coders to spot *all* missing "li" end tags. For although browsers and parsers easily can handle missing "li" end tags (because of the 2014 spec), a missing "li" end tag should never actually be omitted by any professional software engineer caring about "best practices".

Thus, my suggestion is this. If the W3C validator isn't already equipped with "Best Practices" types of warnings/errors, then I am suggesting that the validator should add that to its capabilities. And then it should report all missing "li" end tags as a "Best Practices" type of warning/error.

I am hoping that you can reconsider this proposal, and reinstate it as an active issue.

Have a wonderful day!
Chris Bocay
https://chrisbocay.com/
