### ISSUE TITLE
provide report?

### ISSUE THREAD

**Issue by peepo** [validator/validator#116] opened 2015-07-12 21:03 UTC
is it me?

http://validator.w3.org/nu/?doc=http%3A%2F%2Fwww.peepo.com

Document checking completed.

well yes, but...

ie where is the green favicon, or whatever?

fwiw: requiring http:// is over-pedantic, its the default, else the user can enter....

**Comment by cvrebert** [comment] 2015-07-12 21:06
Duplicate of #109?

**Closed** 2015-07-12 21:10 UTC
