### ISSUE TITLE
CSS validation: missing properties for W3C base.css file

### ISSUE THREAD

**Issue by tidoust** [validator/validator#1154] opened 2021-05-20 21:10 UTC
URL being validated or code to reproduce error:
https://www.w3.org/StyleSheets/TR/2016/base.css

That stylesheet is used in all W3C specs. It contains the following properties that are not yet supported by the validator:

-  `all`
- `text-decoration-skip-ink` (reported in #1132)
- `text-decoration-thickness`
- `border-block-width`

See https://validator.w3.org/nu/?useragent=Validator.nu%2FLV+http%3A%2F%2Fvalidator.w3.org%2Fservices&acceptlanguage=&doc=https%3A%2F%2Fwww.w3.org%2FStyleSheets%2FTR%2F2016%2Fbase.css

Context for this bug is that these styles are also put inline by spec editing tools such as Bikeshed in some configurations. In turn, the [`w3c/spec-prod`](https://github.com/w3c/spec-prod/) action validates inline CSS styles when it builds specs using the validator, and thus reports errors, preventing automated publication of generated specs to GitHub Pages.

**Comment by sideshowbarker** [comment] 2021-05-21 07:21
Fixed now; should now be all green for the following:

https://validator.w3.org/nu/?useragent=Validator.nu%2FLV+http%3A%2F%2Fvalidator.w3.org%2Fservices&acceptlanguage=&doc=https%3A%2F%2Fwww.w3.org%2FStyleSheets%2FTR%2F2016%2Fbase.css

**Closed** 2021-05-21 07:22 UTC
Labels: spec-conformance

**Comment by Robsteranium** [comment] 2021-06-11 11:21
The [spec-prod GitHub Action](https://github.com/w3c/spec-prod/) is using the javascript package instead of the [validator.w3.org/nu](https://validator.w3.org/nu) service so this fix won't get picked-up until a new version (`21.6.9`?) is released on npm. Until then these workflows will fail.

That action doesn't specify a package version. The script shells out to `yarn add vnu-jar`which leads to `21.4.9` at the moment.

I can't seem to see how the npm package is built/ deployed but in any case it looks like the version in `package.json` - `20.6.30` - might be out of sync.

**Comment by sideshowbarker** [comment] 2021-06-11 12:58
I just now released a new npm package, 21.6.11

**Comment by Robsteranium** [comment] 2021-06-11 13:39
That's great. Thanks for the speedy response! 🙇 

I can confirm the workflow succeeds now.
